blank_issues_enabled: false
contact_links:
  - name: 📚 Leia nossa documentação antes de abrir um issue
    url: https://github.com/sua-organizacao/docs
    about: Consulte a documentação antes de abrir um novo problema.
