name: Set status to Product Backlog

on:
  issues:
    types: [opened]

jobs:
  set-status:
    runs-on: ubuntu-latest
    steps:
      - name: Set status in GitHub Project
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const projectNumber = 1; // Número do projeto
            const org = "sua-organizacao-ou-usuario"; // Altere para seu org/user

            const issueId = context.payload.issue.node_id;

            const projectQuery = `
              query {
                organization(login: "${org}") {
                  projectV2(number: ${projectNumber}) {
                    id
                    fields(first: 100) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                        ... on ProjectV2SingleSelectField {
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `;

            const result = await github.graphql(projectQuery);

            const project = result.organization.projectV2;
            const statusField = project.fields.nodes.find(f => f.name === "Status");
            const statusOption = statusField.options.find(o => o.name === "Product Backlog");

            const addItemMutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            const itemResult = await github.graphql(addItemMutation, {
              projectId: project.id,
              contentId: issueId
            });

            const itemId = itemResult.addProjectV2ItemById.item.id;

            const setStatusMutation = `
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `;

            await github.graphql(setStatusMutation, {
              projectId: project.id,
              itemId,
              fieldId: statusField.id,
              optionId: statusOption.id
            });