name: Sync US to Sprint Backlog

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  add-to-sprint-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the US was marked as "Ready"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label.name;

            if (label !== "Ready") {
              console.log("This is not a 'Ready' label. Exiting.");
              return;
            }

            // Define the Sprint Backlog project name
            const sprintProjectName = "Sprint Backlog";

            // Fetch all projects for the repository
            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            // Find the project matching "Sprint Backlog"
            const sprintProject = projects.find(project => project.name === sprintProjectName);
            if (!sprintProject) {
              console.log("Sprint Backlog project not found.");
              return;
            }

            console.log(`Adding Issue #${issue.number} to Sprint Backlog (Project ID: ${sprintProject.id})`);

            // Add the issue to the Sprint Backlog using GraphQL
            const mutation = `
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `;

            const variables = {
              projectId: sprintProject.id,
              contentId: issue.node_id
            };

            const response = await github.graphql(mutation, variables);
            console.log("Successfully added to Sprint Backlog:", response);
