name: Sincronizar US entre Product Backlog e Sprint Backlog

on:
  project_card:
    types: [moved]
  project_item:
    types: [edited]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  sync-backlog-status:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Mudança no Product Backlog
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.project_card.content_url.split('/').pop();
            const { data: issueData } = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue
            });

            const statusField = "Status"; // Nome do campo de status no GitHub Projects
            const sprintProjectName = "Sprint Backlog"; // Nome do Sprint Backlog
            
            // Buscar todos os projetos do repositório
            const { data: projects } = await github.rest.projects.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const sprintProject = projects.find(project => project.name === sprintProjectName);
            if (!sprintProject) {
              console.log("Sprint Backlog não encontrado.");
              return;
            }

            const currentStatus = issueData.labels.map(label => label.name).find(name => name === "Ready");

            if (currentStatus === "Ready") {
              console.log("A US foi movida para Ready. Adicionando ao Sprint Backlog.");

              // Adicionar a US ao Sprint Backlog via GraphQL
              const mutation = `
                mutation($projectId: ID!, $contentId: ID!) {
                  addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                    item {
                      id
                    }
                  }
                }
              `;

              const variables = {
                projectId: sprintProject.id,
                contentId: issueData.node_id
              };

              const response = await github.graphql(mutation, variables);
              console.log("✅ US adicionada ao Sprint Backlog:", response);
            }
