name: Mover US para Sprint Backlog quando estiver "Ready"

on:
  issues:
    types: [edited]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  add-to-sprint-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar Mudança de Status da US
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const updatedField = context.payload.changes;

            // Verifica se o campo Status foi alterado
            if (!updatedField || !updatedField.title) {
              console.log("Nenhuma mudança relevante no Status. Ignorando.");
              return;
            }

            // Buscar o novo Status da US
            const newStatus = issue.labels.map(label => label.name).find(name => name === "Ready");

            if (newStatus === "Ready") {
              console.log("A US foi movida para Ready. Adicionando ao Sprint Backlog.");

              // Adicionar um label "Sprint Backlog" para facilitar o rastreamento
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ["Sprint Backlog"]
              });

              // Criar um comentário confirmando a ação
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: "✅ Esta User Story foi movida automaticamente para o **Sprint Backlog**."
              });
            }
