name: Adicionar US ao Sprint Backlog quando estiver "Ready"

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read
  pull-requests: write
  project: write

jobs:
  add-to-sprint-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se a US foi marcada como "Ready"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label.name;

            if (label === "Ready") {
              console.log("A US foi marcada como 'Ready'. Adicionando ao Sprint Backlog.");

              // Obter todos os projetos da organização ou repositório
              const { data: projects } = await github.rest.projects.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              // Encontrar o ID do projeto "Sprint Backlog"
              const sprintProject = projects.find(project => project.name === "Sprint Backlog");
              if (!sprintProject) {
                console.log("Sprint Backlog não encontrado.");
                return;
              }

              // Adicionar a Issue ao Sprint Backlog
              await github.rest.projects.createCard({
                column_id: sprintProject.id,
                content_id: issue.id,
                content_type: "Issue"
              });

              console.log(`✅ US adicionada ao Sprint Backlog (Project ID: ${sprintProject.id})`);
            }
