name: Mover US para Sprint Backlog quando estiver "Ready"

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: read
  pull-requests: write

jobs:
  move-to-sprint-backlog:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se a US foi marcada como "Ready"
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const label = context.payload.label.name;

            // Se a US foi marcada como "Ready", adicionar ao Sprint Backlog
            if (label === "Ready") {
              console.log("A US foi marcada como 'Ready'. Movendo para Sprint Backlog.");

              // Adicionar um label indicando que a US está no Sprint Backlog
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: ["Sprint Backlog", "Backlog"]
              });

              // Adicionar um comentário automático informando a movimentação
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                body: "✅ Esta User Story foi movida automaticamente para o **Sprint Backlog** e está na coluna **Backlog**."
              });
            }
