name: Test Project Access

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test access to organization projects
        uses: actions/github-script@v7
        env:
          ORG_NAME: ${{ secrets.ORG_NAME }}
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const org = process.env.ORG_NAME;

            const query = `
              query {
                organization(login: "${org}") {
                  projectsV2(first: 10) {
                    nodes {
                      id
                      title
                      number
                    }
                  }
                }
              }
            `;

            const result = await github.graphql(query);

            console.log("✅ Projetos encontrados:");
            result.organization.projectsV2.nodes.forEach(p =>
              console.log(`• [${p.number}] ${p.title} (ID: ${p.id})`)
            );